### ISSUE TITLE
Maven install fails on Xponents 3.4 master

### ISSUE THREAD

**Issue by gtjoumas** [OpenSextant/Xponents#50]
Attempted to run **mvn install** on the latest master code (3.4) which failed with the following error:

[ERROR] Failed to execute goal on project opensextant-xponents: Could not resolve dependencies for project org.opensextant:opensextant-xponents:jar:3.4-SNAPSHOT: Could not find artifact org.opensextant:opensextant-xponents-core:jar:3.4-SNAPSHOT in maven-restlet-talend (https://maven.restlet.talend.com)

**Comment by mubaldino** [comment]
You should have the artifacts for `core` and the main SDK as an outcome of the Build:
https://github.com/OpenSextant/Xponents/blob/master/BUILD.md
The full build from checkout involves visiting more data prep and setup in `./solr/`.

I'm reviewing all of my documentation quarterly.  I was able to get through all of it last time, but even I had some challenges.

**Comment by mubaldino** [comment]
tag `v3.3.3` added to that particular release point.  But if you are building from source, still follow the notes above to checkout that tag or to proceed with develop/master here.   The mention of "talend" repo not having the JAR is a red herring.    I'll have more in a bit.

**Comment by mubaldino** [comment]
FYI release v3.3.5 will be out late this week or early next.   
As a maven project, I'd like to say `mvn install` is the one build command.  I tried using a Parent POM and had two modules in the past.  That did not work well, since the smaller `Core` library became dependent on this monster parent.  

I'd like the versions to stay in lock step with each other, but am desiring some independence of `Core`, so it is much lighter and portable.   Anyhow that is the back story. 

With the build notes in `BUILD.md` does that alone provide a working build for you?

**Comment by gtjoumas** [comment]
I was able to successfully build 3.4-SNAPSHOT following the notes in BUILD.md.

Looking forward to the 3.3.5 build!

**Comment by mubaldino** [comment]
`3.3.5` released.  More updates on documentation per your comments here.   But its far from being as simple as it should be.   Docker images posting now.

**Comment by mubaldino** [comment]
Closing this issue given POM files have changed substantially for the better. 
latest release is now `v3.3.7`. 
Please open a new issue if issues remain.
